/*
 * Ansible Tower API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version:
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// InlineObject81 struct for InlineObject81
type InlineObject81 struct {
	//
	Name string `json:"name"`
	// Organization this label belongs to.
	Organization int32 `json:"organization"`
}
