/*
 * Ansible Tower API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version:
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// InlineObject19 struct for InlineObject19
type InlineObject19 struct {
	//
	CapacityAdjustment float32 `json:"capacity_adjustment,omitempty"`
	//
	Enabled bool `json:"enabled,omitempty"`
	//
	ManagedByPolicy bool `json:"managed_by_policy,omitempty"`
}
