/*
 * Ansible Tower API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version:
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// InlineObject45 struct for InlineObject45
type InlineObject45 struct {
	// Specify the type of credential you want to create. Refer to the Ansible Tower documentation for details on each type.
	CredentialType int32 `json:"credential_type"`
	//
	Description string `json:"description,omitempty"`
	// Enter inputs using either JSON or YAML syntax. Refer to the Ansible Tower documentation for example syntax.
	Inputs map[string]interface{} `json:"inputs,omitempty"`
	//
	Name string `json:"name"`
	// Inherit permissions from organization roles. If provided on creation, do not give either user or team.
	Organization int32 `json:"organization,omitempty"`
}
