/*
 * Ansible Tower API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineObject38 struct for InlineObject38
type InlineObject38 struct {
	// 
	Name string `json:"name"`
	// Organization this label belongs to.
	Organization int32 `json:"organization"`
}
