/*
 * Ansible Tower API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version:
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

// InlineObject23 struct for InlineObject23
type InlineObject23 struct {
	//
	Description string `json:"description,omitempty"`
	//
	Name string `json:"name"`
	// Organization owning this inventory script
	Organization int32 `json:"organization"`
	//
	Script string `json:"script"`
}
