/*
 * Ansible Tower API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version:
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InlineObject22 struct for InlineObject22
type InlineObject22 struct {
	//
	Description *string `json:"description,omitempty"`
	//
	Inventory int32 `json:"inventory"`
	//
	Name string `json:"name"`
	// Group variables in JSON or YAML format.
	Variables *string `json:"variables,omitempty"`
}

// NewInlineObject22 instantiates a new InlineObject22 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject22(inventory int32, name string) *InlineObject22 {
	this := InlineObject22{}
	this.Inventory = inventory
	this.Name = name
	return &this
}

// NewInlineObject22WithDefaults instantiates a new InlineObject22 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject22WithDefaults() *InlineObject22 {
	this := InlineObject22{}
	return &this
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *InlineObject22) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject22) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *InlineObject22) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *InlineObject22) SetDescription(v string) {
	o.Description = &v
}

// GetInventory returns the Inventory field value
func (o *InlineObject22) GetInventory() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Inventory
}

// GetInventoryOk returns a tuple with the Inventory field value
// and a boolean to check if the value has been set.
func (o *InlineObject22) GetInventoryOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Inventory, true
}

// SetInventory sets field value
func (o *InlineObject22) SetInventory(v int32) {
	o.Inventory = v
}

// GetName returns the Name field value
func (o *InlineObject22) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *InlineObject22) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *InlineObject22) SetName(v string) {
	o.Name = v
}

// GetVariables returns the Variables field value if set, zero value otherwise.
func (o *InlineObject22) GetVariables() string {
	if o == nil || o.Variables == nil {
		var ret string
		return ret
	}
	return *o.Variables
}

// GetVariablesOk returns a tuple with the Variables field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject22) GetVariablesOk() (*string, bool) {
	if o == nil || o.Variables == nil {
		return nil, false
	}
	return o.Variables, true
}

// HasVariables returns a boolean if a field has been set.
func (o *InlineObject22) HasVariables() bool {
	if o != nil && o.Variables != nil {
		return true
	}

	return false
}

// SetVariables gets a reference to the given string and assigns it to the Variables field.
func (o *InlineObject22) SetVariables(v string) {
	o.Variables = &v
}

func (o InlineObject22) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if true {
		toSerialize["inventory"] = o.Inventory
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.Variables != nil {
		toSerialize["variables"] = o.Variables
	}
	return json.Marshal(toSerialize)
}

type NullableInlineObject22 struct {
	value *InlineObject22
	isSet bool
}

func (v NullableInlineObject22) Get() *InlineObject22 {
	return v.value
}

func (v *NullableInlineObject22) Set(val *InlineObject22) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject22) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject22) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject22(val *InlineObject22) *NullableInlineObject22 {
	return &NullableInlineObject22{value: val, isSet: true}
}

func (v NullableInlineObject22) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject22) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
