/*
 * Ansible Tower API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineObject10 struct for InlineObject10
type InlineObject10 struct {
	// 
	Description string `json:"description,omitempty"`
	// Is this host online and available for running jobs?
	Enabled bool `json:"enabled,omitempty"`
	// The value used by the remote inventory source to uniquely identify the host
	InstanceId string `json:"instance_id,omitempty"`
	// 
	Inventory int32 `json:"inventory"`
	// 
	Name string `json:"name"`
	// Host variables in JSON or YAML format.
	Variables string `json:"variables,omitempty"`
}
