/*
 * Ansible Tower API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineObject14 struct for InlineObject14
type InlineObject14 struct {
	// Host variables in JSON or YAML format.
	Variables string `json:"variables,omitempty"`
}
