/*
 * Ansible Tower API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineObject64 struct for InlineObject64
type InlineObject64 struct {
	// 
	Description string `json:"description,omitempty"`
	// 
	Name string `json:"name"`
	// 
	Organization int32 `json:"organization"`
}
