/*
 * Ansible Tower API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InlineObject45 struct for InlineObject45
type InlineObject45 struct {
	// Specify the type of credential you want to create. Refer to the Ansible Tower documentation for details on each type.
	CredentialType int32 `json:"credential_type"`
	// 
	Description *string `json:"description,omitempty"`
	// Enter inputs using either JSON or YAML syntax. Refer to the Ansible Tower documentation for example syntax.
	Inputs *map[string]interface{} `json:"inputs,omitempty"`
	// 
	Name string `json:"name"`
	// Inherit permissions from organization roles. If provided on creation, do not give either user or team.
	Organization *int32 `json:"organization,omitempty"`
}

// NewInlineObject45 instantiates a new InlineObject45 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject45(credentialType int32, name string, ) *InlineObject45 {
	this := InlineObject45{}
	this.CredentialType = credentialType
	this.Name = name
	return &this
}

// NewInlineObject45WithDefaults instantiates a new InlineObject45 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject45WithDefaults() *InlineObject45 {
	this := InlineObject45{}
	return &this
}

// GetCredentialType returns the CredentialType field value
func (o *InlineObject45) GetCredentialType() int32 {
	if o == nil  {
		var ret int32
		return ret
	}

	return o.CredentialType
}

// GetCredentialTypeOk returns a tuple with the CredentialType field value
// and a boolean to check if the value has been set.
func (o *InlineObject45) GetCredentialTypeOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.CredentialType, true
}

// SetCredentialType sets field value
func (o *InlineObject45) SetCredentialType(v int32) {
	o.CredentialType = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *InlineObject45) GetDescription() string {
	if o == nil || o.Description == nil {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject45) GetDescriptionOk() (*string, bool) {
	if o == nil || o.Description == nil {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *InlineObject45) HasDescription() bool {
	if o != nil && o.Description != nil {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *InlineObject45) SetDescription(v string) {
	o.Description = &v
}

// GetInputs returns the Inputs field value if set, zero value otherwise.
func (o *InlineObject45) GetInputs() map[string]interface{} {
	if o == nil || o.Inputs == nil {
		var ret map[string]interface{}
		return ret
	}
	return *o.Inputs
}

// GetInputsOk returns a tuple with the Inputs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject45) GetInputsOk() (*map[string]interface{}, bool) {
	if o == nil || o.Inputs == nil {
		return nil, false
	}
	return o.Inputs, true
}

// HasInputs returns a boolean if a field has been set.
func (o *InlineObject45) HasInputs() bool {
	if o != nil && o.Inputs != nil {
		return true
	}

	return false
}

// SetInputs gets a reference to the given map[string]interface{} and assigns it to the Inputs field.
func (o *InlineObject45) SetInputs(v map[string]interface{}) {
	o.Inputs = &v
}

// GetName returns the Name field value
func (o *InlineObject45) GetName() string {
	if o == nil  {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *InlineObject45) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *InlineObject45) SetName(v string) {
	o.Name = v
}

// GetOrganization returns the Organization field value if set, zero value otherwise.
func (o *InlineObject45) GetOrganization() int32 {
	if o == nil || o.Organization == nil {
		var ret int32
		return ret
	}
	return *o.Organization
}

// GetOrganizationOk returns a tuple with the Organization field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject45) GetOrganizationOk() (*int32, bool) {
	if o == nil || o.Organization == nil {
		return nil, false
	}
	return o.Organization, true
}

// HasOrganization returns a boolean if a field has been set.
func (o *InlineObject45) HasOrganization() bool {
	if o != nil && o.Organization != nil {
		return true
	}

	return false
}

// SetOrganization gets a reference to the given int32 and assigns it to the Organization field.
func (o *InlineObject45) SetOrganization(v int32) {
	o.Organization = &v
}

func (o InlineObject45) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["credential_type"] = o.CredentialType
	}
	if o.Description != nil {
		toSerialize["description"] = o.Description
	}
	if o.Inputs != nil {
		toSerialize["inputs"] = o.Inputs
	}
	if true {
		toSerialize["name"] = o.Name
	}
	if o.Organization != nil {
		toSerialize["organization"] = o.Organization
	}
	return json.Marshal(toSerialize)
}

type NullableInlineObject45 struct {
	value *InlineObject45
	isSet bool
}

func (v NullableInlineObject45) Get() *InlineObject45 {
	return v.value
}

func (v *NullableInlineObject45) Set(val *InlineObject45) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject45) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject45) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject45(val *InlineObject45) *NullableInlineObject45 {
	return &NullableInlineObject45{value: val, isSet: true}
}

func (v NullableInlineObject45) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject45) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


