/*
 * Ansible Tower API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// InlineObject19 struct for InlineObject19
type InlineObject19 struct {
	// 
	CapacityAdjustment *float32 `json:"capacity_adjustment,omitempty"`
	// 
	Enabled *bool `json:"enabled,omitempty"`
	// 
	ManagedByPolicy *bool `json:"managed_by_policy,omitempty"`
}

// NewInlineObject19 instantiates a new InlineObject19 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject19() *InlineObject19 {
	this := InlineObject19{}
	return &this
}

// NewInlineObject19WithDefaults instantiates a new InlineObject19 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject19WithDefaults() *InlineObject19 {
	this := InlineObject19{}
	return &this
}

// GetCapacityAdjustment returns the CapacityAdjustment field value if set, zero value otherwise.
func (o *InlineObject19) GetCapacityAdjustment() float32 {
	if o == nil || o.CapacityAdjustment == nil {
		var ret float32
		return ret
	}
	return *o.CapacityAdjustment
}

// GetCapacityAdjustmentOk returns a tuple with the CapacityAdjustment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject19) GetCapacityAdjustmentOk() (*float32, bool) {
	if o == nil || o.CapacityAdjustment == nil {
		return nil, false
	}
	return o.CapacityAdjustment, true
}

// HasCapacityAdjustment returns a boolean if a field has been set.
func (o *InlineObject19) HasCapacityAdjustment() bool {
	if o != nil && o.CapacityAdjustment != nil {
		return true
	}

	return false
}

// SetCapacityAdjustment gets a reference to the given float32 and assigns it to the CapacityAdjustment field.
func (o *InlineObject19) SetCapacityAdjustment(v float32) {
	o.CapacityAdjustment = &v
}

// GetEnabled returns the Enabled field value if set, zero value otherwise.
func (o *InlineObject19) GetEnabled() bool {
	if o == nil || o.Enabled == nil {
		var ret bool
		return ret
	}
	return *o.Enabled
}

// GetEnabledOk returns a tuple with the Enabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject19) GetEnabledOk() (*bool, bool) {
	if o == nil || o.Enabled == nil {
		return nil, false
	}
	return o.Enabled, true
}

// HasEnabled returns a boolean if a field has been set.
func (o *InlineObject19) HasEnabled() bool {
	if o != nil && o.Enabled != nil {
		return true
	}

	return false
}

// SetEnabled gets a reference to the given bool and assigns it to the Enabled field.
func (o *InlineObject19) SetEnabled(v bool) {
	o.Enabled = &v
}

// GetManagedByPolicy returns the ManagedByPolicy field value if set, zero value otherwise.
func (o *InlineObject19) GetManagedByPolicy() bool {
	if o == nil || o.ManagedByPolicy == nil {
		var ret bool
		return ret
	}
	return *o.ManagedByPolicy
}

// GetManagedByPolicyOk returns a tuple with the ManagedByPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject19) GetManagedByPolicyOk() (*bool, bool) {
	if o == nil || o.ManagedByPolicy == nil {
		return nil, false
	}
	return o.ManagedByPolicy, true
}

// HasManagedByPolicy returns a boolean if a field has been set.
func (o *InlineObject19) HasManagedByPolicy() bool {
	if o != nil && o.ManagedByPolicy != nil {
		return true
	}

	return false
}

// SetManagedByPolicy gets a reference to the given bool and assigns it to the ManagedByPolicy field.
func (o *InlineObject19) SetManagedByPolicy(v bool) {
	o.ManagedByPolicy = &v
}

func (o InlineObject19) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.CapacityAdjustment != nil {
		toSerialize["capacity_adjustment"] = o.CapacityAdjustment
	}
	if o.Enabled != nil {
		toSerialize["enabled"] = o.Enabled
	}
	if o.ManagedByPolicy != nil {
		toSerialize["managed_by_policy"] = o.ManagedByPolicy
	}
	return json.Marshal(toSerialize)
}

type NullableInlineObject19 struct {
	value *InlineObject19
	isSet bool
}

func (v NullableInlineObject19) Get() *InlineObject19 {
	return v.value
}

func (v *NullableInlineObject19) Set(val *InlineObject19) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject19) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject19) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject19(val *InlineObject19) *NullableInlineObject19 {
	return &NullableInlineObject19{value: val, isSet: true}
}

func (v NullableInlineObject19) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject19) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


